### ISSUE TITLE
Auction Date 

### ISSUE THREAD

**Issue by spb2445** [spb2445/kansas-city-tow-lots#8]
Display the third Tuesday of the month without manually changing each month.

**Comment by spb2445** [comment]
Unfortunately, I don't have it working yet. But I haven't looked at this component for a month or so.

**Comment by Mhart12** [comment]
Huh well it seems to be working fine to me. It has Sept. 18th as the next date which is correct.

**Comment by spb2445** [comment]
Try to change the date manually to Sept. 19th and see what it has the auction date as. Hopefully it shows Oct. 16.

**Comment by Mhart12** [comment]
Ok I'll take a look
